### PR TITLE
DarwishQuiambao Solution

### PR DESCRIPTION
**Pull request by aGzDelusion**
Included pictures for my Profile Page and some CSS as well inside the interns folder. lock-logic.js is also commented on for the added lines. @nihwang @metalsheep @rkofman-lob @sasha-ashpis

### CODE REVIEW

**Comment by aGzDelusion** [comment]
Having issues privatizing and creating a pull request based on duplicate/mirrored repo

**Comment by nynaalekhya** [comment]
Hey @aGzDelusion,
You could use this documentation https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/duplicating-a-repository

**Comment by aGzDelusion** [comment]
Hi,

Thank you for your feedback. I’ll make sure to do check it out as soon as I
get back home tonight.

**Comment by nynaalekhya** [comment]
@aGzDelusion I used this resource to submit my application.

**Pull request closed without merging**
