### PR TITLE
Lob Technical Challenge

### PR DESCRIPTION
**Pull request by moeezk7**
Thanks for your consideration!

### CODE REVIEW

**Comment by moeezk7** [comment]
@nihwang @metalsheep @rkofman-lob @sasha-ashpis

**Comment by rkofman-lob** [comment]
Hi, please re-submit your application with a link to a PR between two branches in a private duplicate of this repo (per the readme.md instructions)

**Comment by moeezk7** [comment]
@rkofman-lob Hello,
I tried to do that originally but it seemingly does not allow me to create a pull request between this repo and my private duplicated repo. I tried to research this online and still could not find a way to do it.

**Comment by moeezk7** [comment]
I sincerely apologize about the misunderstanding. I have followed the instructions and will re-submit my application. Thanks!

**Pull request closed without merging**
