### PR TITLE
Finished Coding

### PR DESCRIPTION
**Pull request by jkawamura**

### CODE REVIEW

**Comment by jkawamura** [comment]
@nihwang @metalsheep @rkofman-lob @sasha-ashpis (couldn't add reviewers on the side)

**Comment by metalsheep** [comment]
Please re-submit this per the instructions in readme.md - in a private duplicate of this repo as a PR between two branches.

**Comment by jkawamura** [comment]
> 
> 
> Please re-submit this per the instructions in readme.md - in a private duplicate of this repo as a PR between two branches.

I have created a private repo and made a PR. Should I send the link to you?

**Comment by metalsheep** [comment]
All good I was able to find it.

**Pull request closed without merging**
